stages:
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: java:8-jdk
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
  tags:
   - Docker    

deploy:
  stage: deploy

  script:
    - echo "$DAEKGIL_SSH_KEY" > daekgil.ppk
    - chmod 400 daekgil.ppk
    # - ssh daekgil@devj.io -T -p 222 -o StrictHostKeyChecking=no -i daekgil.ppk 
    #   "docker stop tomcat &&
    #   mv /home/daekgil/tomcat/temp/blog/ROOT.war /home/daekgil/tomcat/webapps/blog/ROOT.war &&
    #   docker start tomcat"
  only:
    - master    
  tags:
   - Shell    