stages:
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: java:8-jdk
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
  tags:
   - Docker    

deploy:
  stage: deploy

  script:
    - echo "$DEVJ_SSH_KEY" > devj.ppk
    - chmod 400 devj.ppk
    - chmod +x -R build

    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -i devj.ppk build/libs/restful-0.0.1.jar devj@devj.io:/home/devj/docker/restful_api/ROOT.jar

    - ssh devj@devj.io -T -p $SSH_PORT -o StrictHostKeyChecking=no -i devj.ppk 
      "cd /home/devj/docker/restful_api 
       && docker-compose build 
       && docker-compose up -d"
  only:
    - master    
  tags:
   - Shell    